# **(( REGION ANALYSIS ))**

# **OBJECTIVE :**



**Q1: Is regional account distribution driven by chance,
or do specific regions have a significantly higher bank presence?**


*    H0: Account distribution is uniform across all regions
*    H1: Distribution is not uniform — regional factors exist

---
**Q2: Which regions show the highest demand
for the bank's services ?**


*   H0: penetration rate is uniform across all regions
*   H1: Penetration rate varies by region

---
**Q3: Do regions differ in monthly financial behavior
as measured by average monthly net balance (B/M)?**


*   H0: Monthly net balance is identical across all regions
*   H1: At least one region differs significantly

---

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
from scipy.stats import chisquare
from scipy.stats import chi2_contingency
import statsmodels.stats.proportion as prop

# **DATA EXTRACTION :**

**TABLE 1**

In [ ]:
CSV_Files_url = "https://raw.githubusercontent.com/aliabedalkereem-byte/Data-Analytics-Portfolio/main/4_Berka-Database-Analysis/CSV_Files/"

BASIC= pd.read_csv(CSV_Files_url  + "BASIC.csv")
ORDER= pd.read_csv(CSV_Files_url + "ORDER.csv")

In [ ]:
basic1=BASIC.copy()
order1=ORDER.copy()

T=basic1.merge(order1,how='inner',on='account_id')[['account_id','region','ORDERS','Sipo_Order','Uver_Order','Leasing_Order','Pojistne_Order','Other_Order']]
T1=T.rename( columns={ 'region':'Region','Sipo_Order': 'Utility','Uver_Order':'Loan','Pojistne_Order':'Insurance','Leasing_Order':'Leasing','Other_Order':'Other'})

TABLE1 = T1.groupby('Region',as_index=False).agg(
    Total_Accounts=('account_id', 'count'),
    Utility=('Utility', lambda x: (x > 0).value_counts().get(True, 0)),
    Loan=('Loan', lambda x: (x > 0).value_counts().get(True, 0)),
    Leasing=('Leasing', lambda x: (x > 0).value_counts().get(True, 0)),
    Insurance=('Insurance', lambda x: (x > 0).value_counts().get(True, 0)),
    Other=('Other', lambda x: (x > 0).value_counts().get(True, 0)))

TABLE1[:]

            Region  Total_Accounts  Utility  Loan  Leasing  Insurance  Other
0           Prague             554      417    86       50         70    153
1  central Bohemia             574      437    95       50         68    152
2     east Bohemia             544      385    89       40         51    125
3    north Bohemia             457      358    65       37         61    131
4    north Moravia             793      595   123       60         98    194
5    south Bohemia             370      273    64       20         43     99
6    south Moravia             778      565   131       58         95    223
7     west Bohemia             430      335    64       26         46    121

**TABLE 2**

In [ ]:
###  (Database Connection & Initial Extraction of Berka Transaction Data) ###

#!pip install pandas sqlalchemy mysql-connector-python
#from sqlalchemy import create_engine
#db_connection_str = 'mysql+mysqlconnector://guest:ctu-relational@relational.fel.cvut.cz/financial'
#db_connection = create_engine(db_connection_str)
#trans= pd.read_sql("SELECT * FROM financial.trans", db_connection)
#trans.to_csv("TRANS.csv", index=False)

In [ ]:
CSV_files_url = "https://raw.githubusercontent.com/aliabedalkereem-byte/Data-Analytics-Portfolio/main/5_Berka-Database-Deep-Analysis/CSV_files/"

TRANS= pd.read_csv(CSV_files_url  + "TRANS.csv")

/tmp/ipykernel_486/2360837206.py:3: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  TRANS= pd.read_csv(CSV_files_url  + "TRANS.csv")

In [ ]:
trans1=TRANS.copy()
# simplified trans table
trans1['date']=pd.to_datetime(trans1['date'])
trans2=trans1[['account_id','date','type','amount']]
trans2=trans2.sort_values(by=['account_id','date'])
trans2['IN'] =np.where(trans2['type']=='PRIJEM',trans2['amount'],0)
trans2['OUT'] =np.where((trans2['type']=='VYDAJ')|(trans2['type']=='VYBER'),trans2['amount'],0)
trans2[:]
# groub by account cn:IN,OUT,B
trans3=trans2.groupby(['account_id'],as_index=False).agg({'IN' :'sum','OUT' : 'sum'})
trans3['B']=trans3['IN']-trans3['OUT']
trans3[:]
# period (P)
months_count=trans2.copy()
months_count=months_count.groupby('account_id',as_index=False)['date'].agg({'min' , 'max'})
months_count['Months_Count']=(months_count['max'].dt.year - months_count['min'].dt.year)*12 + (months_count['max'].dt.month - months_count['min'].dt.month)
months_count1=months_count[['account_id','Months_Count']]
months_count1[:]
# merge cn:IN,OUT,B,P,IN/P,OUT/P,B/P
TABLE=trans3.merge(months_count1,how='inner',on='account_id')
TABLE['IN/M']=TABLE['IN'] / TABLE['Months_Count']
TABLE['OUT/M']=TABLE['OUT'] / TABLE['Months_Count']
TABLE['B/M']=TABLE['B'] / TABLE['Months_Count']
TABLE[:]  #TABLE.to_csv("TRANS_grouped.csv", index=False)
# TABLE2
T2=TABLE.merge(BASIC,how='inner',on='account_id')[['account_id','IN','OUT','B','Months_Count','IN/M','OUT/M','B/M','region']]
TABLE2=T2.groupby(['region','account_id']).agg({'B/M':'sum'})

TABLE2

                                 B/M
region       account_id
Prague       2            608.514286
             17          4255.478261
             22           626.701754
             36          1217.338462
             49           765.250000
...                              ...
west Bohemia 10351        347.604651
             10365       1417.076923
             10915        962.818182
             10954       1487.931034
             11096       2707.791667

[4500 rows x 1 columns]

# **ANALYSIS :**

# **Q1**

In [ ]:
A=TABLE1[['Region','Total_Accounts']].copy()

total_accounts = A['Total_Accounts'].sum()
expected_baseline = total_accounts / len(A)

# Chi-Square Goodness-Of-Fit Test
stat, p_value = chisquare(A['Total_Accounts'])

print("#Chi-Square Goodness-Of-Fit Test Results :")
print(f"  Chi-Square Statistic: {stat:.2f}")
print(f"  P-Value: {p_value:.5e}\n")

if p_value < 0.05:
    print("-Verdict: STATISTICALLY SIGNIFICANT")
    print("-The accounts are NOT evenly spread out by chance. We have clear regional strongholds!")
else:
    print("-Verdict: NOT SIGNIFICANT")
    print("-The accounts distribution is roughly equal across all regions.")

# Standardized Residual Analysis
A['Z_Score'] = (A['Total_Accounts'] - expected_baseline) / np.sqrt(expected_baseline)

def classify_regional_density(score):
    if score > 2:
        return "SIGNIFICANTLY ABOVE EXPECTED"
    elif score < -2:
        return " SIGNIFICANTLY BELOW EXPECTED"
    else:
        return "WITHIN EXPECTED RANGE"

A['Regional_Status'] = A['Z_Score'].apply(classify_regional_density)

# Wilson Score Confidence Interval for Proportions.
A['Current_%'] =(A['Total_Accounts'] / total_accounts) * 100

lower_bound_prop, upper_bound_prop = prop.proportion_confint(A['Total_Accounts'], total_accounts, alpha=0.05, method='wilson')
A['%_CI_Lower'] = lower_bound_prop * 100
A['%_CI_Upper'] = upper_bound_prop * 100

# RESULTS
print('................................................................................................................')
print('................................................................................................................')
print(A[['Region','Total_Accounts','Regional_Status','Current_%','%_CI_Lower','%_CI_Upper']].to_string(index=False))

#Chi-Square Goodness-Of-Fit Test Results :
  Chi-Square Statistic: 294.86
  P-Value: 7.56406e-60

-Verdict: STATISTICALLY SIGNIFICANT
-The accounts are NOT evenly spread out by chance. We have clear regional strongholds!
................................................................................................................
................................................................................................................
         Region  Total_Accounts               Regional_Status  Current_%  %_CI_Lower  %_CI_Upper
         Prague             554         WITHIN EXPECTED RANGE  12.311111   11.383147   13.303367
central Bohemia             574         WITHIN EXPECTED RANGE  12.755556   11.812544   13.762101
   east Bohemia             544         WITHIN EXPECTED RANGE  12.088889   11.168599   13.073849
  north Bohemia             457  SIGNIFICANTLY BELOW EXPECTED  10.155556    9.306712   11.072368
  north Moravia             793  SIGNIFICANTLY ABOVE EXPECTED  17.622222   16.536760   18.762916
  south Bohemia             370  SIGNIFICANTLY BELOW EXPECTED   8.222222    7.454796    9.060916
  south Moravia             778  SIGNIFICANTLY ABOVE EXPECTED  17.288889   16.212048   18.421530
   west Bohemia             430  SIGNIFICANTLY BELOW EXPECTED   9.555556    8.730790   10.449314

# **Q2**

In [ ]:
B=TABLE1.copy()
ORDERS = ['Utility', 'Loan', 'Leasing', 'Insurance', 'Other']

print('Orders Demand & Penetration:')
print('....................................')
# Chi-Square Test of Independence
for O in ORDERS:
    has_order = B[O]
    no_order = B['Total_Accounts'] - B[O]

    O_matrix = np.array([has_order, no_order])

    chi2, p_val, dof, expected = chi2_contingency(O_matrix)

    print(f"##ORDER Category: {O}")
    print(f"  -Chi-Square Stat : {chi2:.2f}")
    print(f"  -P-Value: {p_val:.4f}")

    if p_val < 0.05:
        print("  -Verdict:  SIGNIFICANT DIFFERENCE . The  rate shifts by regions.")
    else:
        print("  -Verdict:  NO SIGNIFICANT DIFFERENCE. The rate is uniform across regions.")
    print("=" * 60)

Orders Demand & Penetration:
....................................
##ORDER Category: Utility
  -Chi-Square Stat : 12.70
  -P-Value: 0.0798
  -Verdict:  NO SIGNIFICANT DIFFERENCE. The rate is uniform across regions.
============================================================
##ORDER Category: Loan
  -Chi-Square Stat : 2.75
  -P-Value: 0.9068
  -Verdict:  NO SIGNIFICANT DIFFERENCE. The rate is uniform across regions.
============================================================
##ORDER Category: Leasing
  -Chi-Square Stat : 6.87
  -P-Value: 0.4421
  -Verdict:  NO SIGNIFICANT DIFFERENCE. The rate is uniform across regions.
============================================================
##ORDER Category: Insurance
  -Chi-Square Stat : 5.36
  -P-Value: 0.6156
  -Verdict:  NO SIGNIFICANT DIFFERENCE. The rate is uniform across regions.
============================================================
##ORDER Category: Other
  -Chi-Square Stat : 9.02
  -P-Value: 0.2511
  -Verdict:  NO SIGNIFICANT DIFFERENCE. The rate is uniform across regions.
============================================================

# **Q3**

In [ ]:
C = TABLE2.reset_index()

regional_summary = C.groupby('region')['B/M'].agg(['count', 'mean', 'median', 'std'])

print("REGIONAL NUMERICAL SUMMARY:")
print('=============================')
print(regional_summary.round(2))

REGIONAL NUMERICAL SUMMARY:
=============================
                 count     mean   median      std
region
Prague             554  1357.23  1130.64   996.46
central Bohemia    574  1360.96  1049.56  1083.03
east Bohemia       544  1338.58  1081.04  1040.10
north Bohemia      457  1323.79  1084.56   972.96
north Moravia      793  1312.19  1020.92  1007.10
south Bohemia      370  1302.27  1009.40  1026.37
south Moravia      778  1330.89  1094.96  1002.23
west Bohemia       430  1278.20  1082.12   909.41

In [ ]:
## NORMALITY CHECK
# SHAPIRO-WILK NORMALITY TEST
print("SHAPIRO-WILK NORMALITY TEST RESULTS (B/M Column):")
print("=" * 65)

for name, group in C.groupby('region'):
    values = group['B/M'].values

    stat2, p_val2 = stats.shapiro(values)

    print(f"##REGION: {name}")
    print(f"   -Shapiro Stat : {stat2:.2f}")
    print(f"   -P-Value      : {p_val2:.4f}")

    if p_val2 < 0.05:
        print(" . Verdict:  NOT NORMALLY DISTRIBUTED (Significantly skewed)")
    else:
        print(" . Verdict:  NORMALLY DISTRIBUTED (Passes normality assumption)")
    print("—" * 65)

SHAPIRO-WILK NORMALITY TEST RESULTS (B/M Column):
=================================================================
##REGION: Prague
   -Shapiro Stat : 0.89
   -P-Value      : 0.0000
 . Verdict:  NOT NORMALLY DISTRIBUTED (Significantly skewed)
—————————————————————————————————————————————————————————————————
##REGION: central Bohemia
   -Shapiro Stat : 0.85
   -P-Value      : 0.0000
 . Verdict:  NOT NORMALLY DISTRIBUTED (Significantly skewed)
—————————————————————————————————————————————————————————————————
##REGION: east Bohemia
   -Shapiro Stat : 0.85
   -P-Value      : 0.0000
 . Verdict:  NOT NORMALLY DISTRIBUTED (Significantly skewed)
—————————————————————————————————————————————————————————————————
##REGION: north Bohemia
   -Shapiro Stat : 0.88
   -P-Value      : 0.0000
 . Verdict:  NOT NORMALLY DISTRIBUTED (Significantly skewed)
—————————————————————————————————————————————————————————————————
##REGION: north Moravia
   -Shapiro Stat : 0.84
   -P-Value      : 0.0000
 . Verdict:  NOT NORMALLY DISTRIBUTED (Significantly skewed)
—————————————————————————————————————————————————————————————————
##REGION: south Bohemia
   -Shapiro Stat : 0.84
   -P-Value      : 0.0000
 . Verdict:  NOT NORMALLY DISTRIBUTED (Significantly skewed)
—————————————————————————————————————————————————————————————————
##REGION: south Moravia
   -Shapiro Stat : 0.86
   -P-Value      : 0.0000
 . Verdict:  NOT NORMALLY DISTRIBUTED (Significantly skewed)
—————————————————————————————————————————————————————————————————
##REGION: west Bohemia
   -Shapiro Stat : 0.86
   -P-Value      : 0.0000
 . Verdict:  NOT NORMALLY DISTRIBUTED (Significantly skewed)
—————————————————————————————————————————————————————————————————

In [ ]:
## VARIANCE CHECK
# LEVENE'S TEST FOR HOMOGENEITY OF VARIANCE
region_groups = [group['B/M'].values for name, group in C.groupby('region')]

levene_stat, levene_p = stats.levene(*region_groups, center='median')

print("LEVENE'S TEST FOR HOMOGENEITY OF VARIANCE:")
print("=" * 65)
print(f" -Levene Stat: {levene_stat:.2f}")
print(f" -P-Value   : {levene_p:.4f}")
print("—" * 65)

if levene_p < 0.05:
    print(". Verdict: HETEROSCEDASTICITY (Variances / spreads differ significantly by region)")
else:
    print(". Verdict: HOMOSCEDASTICITY (Variances are uniform; distribution shapes match)")
print("—" * 65)

LEVENE'S TEST FOR HOMOGENEITY OF VARIANCE:
=================================================================
 -Levene Stat: 0.76
 -P-Value   : 0.6181
—————————————————————————————————————————————————————————————————
. Verdict: HOMOSCEDASTICITY (Variances are uniform; distribution shapes match)
—————————————————————————————————————————————————————————————————

In [ ]:
# KRUSKAL-WALLIS TEST
R_groups = [group['B/M'].values for name, group in C.groupby('region')]

stat3, p_val3 = stats.kruskal(*R_groups)

print("KRUSKAL-WALLIS TEST RESULTS FOR B/M (NON-PARAMETRIC):")
print("=" * 65)
print(f" -H-Statistic : {stat3:.2f}")
print(f" -P-Value     : {p_val3:.4f}")
print("—" * 65)

if p_val3 < 0.05:
    print("  . Verdict: SIGNIFICANT DIFFERENCE! The regional B/M medians vary significantly.")
else:
    print("  . Verdict: UNIFORM DISTRIBUTION! The regional B/M medians are statistically identical.")
print("—" * 65)

KRUSKAL-WALLIS TEST RESULTS FOR B/M (NON-PARAMETRIC):
=================================================================
 -H-Statistic : 1.88
 -P-Value     : 0.9661
—————————————————————————————————————————————————————————————————
  . Verdict: UNIFORM DISTRIBUTION! The regional B/M medians are statistically identical.
—————————————————————————————————————————————————————————————————